config/routes.rb
# == Route Map
#
#                   Prefix Verb   URI Pattern                      Controller#Action
#                  seasons GET    /seasons(.:format)               seasons#index
#                          POST   /seasons(.:format)               seasons#create
#               new_season GET    /seasons/new(.:format)           seasons#new
#              edit_season GET    /seasons/:id/edit(.:format)      seasons#edit
#                   season GET    /seasons/:id(.:format)           seasons#show
#                          PATCH  /seasons/:id(.:format)           seasons#update
#                          PUT    /seasons/:id(.:format)           seasons#update
#                          DELETE /seasons/:id(.:format)           seasons#destroy
#         new_user_session GET    /users/sign_in(.:format)         devise/sessions#new
#             user_session POST   /users/sign_in(.:format)         devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)        devise/sessions#destroy
#        new_user_password GET    /users/password/new(.:format)    devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)   devise/passwords#edit
#            user_password PATCH  /users/password(.:format)        devise/passwords#update
#                          PUT    /users/password(.:format)        devise/passwords#update
#                          POST   /users/password(.:format)        devise/passwords#create
# cancel_user_registration GET    /users/cancel(.:format)          devise/registrations#cancel
#    new_user_registration GET    /users/sign_up(.:format)         devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)            devise/registrations#edit
#        user_registration PATCH  /users(.:format)                 devise/registrations#update
#                          PUT    /users(.:format)                 devise/registrations#update
#                          DELETE /users(.:format)                 devise/registrations#destroy
#                          POST   /users(.:format)                 devise/registrations#create
#                     root GET    /                                marina#home
#                     home GET    /home(.:format)                  marina#home
#                 boatramp GET    /boatramp(.:format)              marina#boatramp
#                 contacts GET    /contacts(.:format)              contacts#new
#                    index GET    /index(.:format)                 marina#index
#                 batplass GET    /batplass(.:format)              marina#berths
#                tjenester GET    /tjenester(.:format)             marina#services
#                          GET    /contacts(.:format)              contacts#new
#                          POST   /contacts(.:format)              contacts#create
#              new_contact GET    /contacts/new(.:format)          contacts#new
#             berth_orders GET    /berth_orders(.:format)          berth_orders#index
#                          POST   /berth_orders(.:format)          berth_orders#create
#          new_berth_order GET    /berth_orders/new(.:format)      berth_orders#new
#         edit_berth_order GET    /berth_orders/:id/edit(.:format) berth_orders#edit
#              berth_order GET    /berth_orders/:id(.:format)      berth_orders#show
#                          PATCH  /berth_orders/:id(.:format)      berth_orders#update
#                          PUT    /berth_orders/:id(.:format)      berth_orders#update
#                          DELETE /berth_orders/:id(.:format)      berth_orders#destroy
#                    boats GET    /boats(.:format)                 boats#index
#                          POST   /boats(.:format)                 boats#create
#                 new_boat GET    /boats/new(.:format)             boats#new
#                edit_boat GET    /boats/:id/edit(.:format)        boats#edit
#                     boat GET    /boats/:id(.:format)             boats#show
#                          PATCH  /boats/:id(.:format)             boats#update
#                          PUT    /boats/:id(.:format)             boats#update
#                          DELETE /boats/:id(.:format)             boats#destroy
#                    users GET    /users(.:format)                 users#index
#                          POST   /users(.:format)                 users#create
#                 new_user GET    /users/new(.:format)             users#new
#                edit_user GET    /users/:id/edit(.:format)        users#edit
#                     user GET    /users/:id(.:format)             users#show
#                          PATCH  /users/:id(.:format)             users#update
#                          PUT    /users/:id(.:format)             users#update
#                          DELETE /users/:id(.:format)             users#destroy
#                          GET    /                                marina#home

Rails.application.routes.draw do

  resources :seasons
  devise_for :users

  root 'marina#home'
  # Static pages:
  get 'home', to: 'marina#home'
  get 'boatramp', to: 'marina#boatramp'
  get 'contacts', to: 'contacts#new'
  get 'index', to: 'marina#index'
  get 'batplass', to: 'marina#berths'
  get 'tjenester', to: 'marina#services'

  match '/contacts',  to: 'contacts#new', via: 'get'
  resources "contacts", only: [:new, :create]


  resources :berth_orders
  resources :boats
  resources :users
  root 'marina#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/berth_order.rb
# == Schema Information
#
# Table name: berth_orders
#
#  id        :bigint(8)        not null, primary key
#  boat_id   :bigint(8)
#  season_id :bigint(8)
#  status_id :bigint(8)
#

class BerthOrder < ApplicationRecord

	validates :boat, presence: true
	validates :season, presence: true

	belongs_to :boat
	belongs_to :season
  belongs_to :status

	accepts_nested_attributes_for :boat
	accepts_nested_attributes_for :season

end

app/controllers/berth_orders_controller.rb
class BerthOrdersController < LoggedInController
  before_action :set_berth_order, only: [:show, :edit, :update, :destroy]


  # GET /berth_orders
  # GET /berth_orders.json
  def index
    if current_user.admin?
      @berth_orders = BerthOrder.all
    else
      @berth_orders = current_user.berth_orders
    end
  end

  # GET /berth_orders/1
  # GET /berth_orders/1.json
  def show
  end

  # GET /berth_orders/new
  def new
    @berth_order = BerthOrder.new
    @boat = Boat.new
    @user_boats = current_user.boats
    @current_seasons = Season.bookable_seasons

    # To see how many berths are available in a given season:
    new_current_seasons = {}
    @current_seasons.each do |season|
      new_current_seasons[season.id] = season.as_json
      new_current_seasons[season.id]["available_berths"] = season.available_berths
    end

    @formatted_seasons = new_current_seasons.to_json
  end

  # GET /berth_orders/1/edit
  def edit
    season_id = BerthOrder.find(params[:id]).season_id
    @available_berths = Season.find(season_id).berths - BerthOrder.where(season_id: season_id, status_id: 1).count
    @status = Status.all
    @current_seasons = Season.bookable_seasons

  end

  # POST /berth_orders
  # POST /berth_orders.json
  def create
    @berth_order = BerthOrder.new
    @berth_order.status = Status.find_by(status: "Under behandling")
    if berth_order_params["boat_id"].blank?
      @boat = Boat.new
      @boat.name = params[:boat][:name]
      @boat.width = params[:boat][:width].gsub(',', '.')
      @boat.user = current_user
      @boat.save
      @berth_order.boat = @boat
    else
      @berth_order.boat_id = berth_order_params[:boat_id]
    end

    @berth_order.season_id = berth_order_params[:season_id]

    #.. And finally:
    respond_to do |format|
      if @berth_order.save
        format.html { redirect_to @berth_order, notice: 'Berth order was successfully created.' }
        format.json { render :show, status: :created, location: @berth_order }
      else
        format.html { render :new }
        format.json { render json: @berth_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /berth_orders/1
  # PATCH/PUT /berth_orders/1.json
  def update
    binding.pry
    respond_to do |format|
      if @berth_order.update(berth_order_params)
        format.html { redirect_to berth_orders_path, notice: 'Berth order was successfully updated.' }
        format.json { render :show, status: :ok, location: @berth_order }
      else
        format.html { render :edit }
        format.json { render json: @berth_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /berth_orders/1
  # DELETE /berth_orders/1.json
  def destroy
    @berth_order.destroy
    respond_to do |format|
      format.html { redirect_to berth_orders_url, notice: 'Berth order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_berth_order
      @berth_order = BerthOrder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def berth_order_params
      params.require(:berth_order).permit(:boat_id, :season_id, :status_id)
    end

end

app/helpers/berth_orders_helper.rb
module BerthOrdersHelper

  def bookable_seasons
    Season.bookable_seasons
  end
end

app/views/berth_orders/_admin_form.html.haml
%div.container
  = form_for @berth_order do |f|
    - if @berth_order.errors.any?
      #error_explanation
        %h2= "#{@berth_order.errors.count} feil hindret denne bestillingen fra å bli lagret:"
        %ul
          - @berth_order.errors.full_messages.each do |message|
            %li= message

    %div.form-row
      %div.col
        %div.row
          .field
            -if current_user.admin?
              = f.label :user, 'Båteier:'
              = @berth_order.boat.user.email
        %div.row
          .field
            = f.label :name, 'Båtnavn:'
            - if current_user.admin?
              = f.label @berth_order.boat.name
            - else
              -# TODO: Sjekke om listen er tom, og isåfall kun vise linken under.
              = f.collection_select(:boat_id, @user_boats, :id, :name)
              .field
                %i
                  = link_to "Legg til båt", new_boat_path, class: "text-primary"
            .field
              = f.label :season, 'Sesong:'
              - if current_user.admin?
                = f.label @berth_order.season.title
              - else
                = f.collection_select(:season_id, bookable_seasons, :id, :title)
      %div.col
        %div.row
        -if current_user.admin?
          %div.row
            .field
              = f.label 'Antall ledige plasser:'
              = f.label @available_berths
          %div.row
            .field
              = f.label :status, 'Status:'
              = f.collection_select(:status_id, @status, :id, :status)
    %div.row
      .actions
        = f.submit 'Lagre', class: "btn btn-primary btn-lg text-light btn-sm"
        = link_to 'Tilbake', berth_orders_path, class: "btn btn-primary btn-lg text-light btn-sm"

app/views/berth_orders/_form.html.haml
= render 'step_guide'

:javascript
  $(document).ready(berth_order_form);

%div.container
  %div.content
    %div.main

      = form_for @berth_order, html: {id: "berthOrderForm"} do |f|
        - if @berth_order.errors.any?
          #error_explanation
            %h2= "#{@berth_order.errors.count} feil hindret denne bestillingen fra å bli lagret:"
            %ul
              - @berth_order.errors.full_messages.each do |message|
                %li= message

        #boatValidation

        %div#seasonTab
          - if @current_seasons
            %fieldset.text-center
              = f.collection_select(:season_id, @current_seasons, :id, :to_s)
            %fieldset.text-center
              Tilgjengelige båtplasser:
              = content_tag "div", id: "seasons", data: {"seasons": @formatted_seasons} do
                #availableBerths


        %div#boatTab
          = fields_for :boat do |builder|
            = builder.label :name, "Båtnavn"
            = builder.text_field :name
            = builder.label :width, "Båtbredde"
            = builder.text_field :width

          - if @user_boats.present?
            %fieldset.text-center
              = f.label :boat, "Eller velg en av dine båter:"
              %br
              -if @user_boats
                = f.collection_select(:boat_id, @user_boats, :id,
                                       :name, {include_blank: "--Velg båt--"}, {:id=>"boatDrop"})






        = submit_tag 'Fortsett', id: "nextBtn", class: "hide", type: 'button'
        = submit_tag "Tilbake", id: "prevBtn", class: "hide", type: 'button'
        = f.submit 'Fullfør', id: "completeBtn", class: "hide"

app/views/berth_orders/_step_guide.haml
%div.container
  %ul.progressbar#progressbar
    %li.listItem Velg sesong
    %li.listItem Velg båt
    %li.listItem Oppsummering

app/views/berth_orders/assign_berth.haml
%h1 Hello.

app/views/berth_orders/edit.html.haml
%div.container
  %h1 Endre båtplassbestilling
  - if current_user.admin?
    = render 'admin_form'
  - else
    = render 'form'

app/views/berth_orders/index.html.haml
%div.container
  %h1 Båtplassbestillinger

  %table.table
    %thead
      %tr
        %th{scope: "col"} Ordrenummer
        %th{scope: "col"} Båtnavn
        %th{scope: "col"} Sesong
        %th{scope: "col"} Status
        - if current_user.admin?
          %th{scope: "col"} Båteier
        %th
        %th
        %th

    %tbody
      - @berth_orders.each do |berth_order|
        %tr
          %td= berth_order.id
          %td= berth_order&.boat&.name
          %td
            = berth_order.season.title
            (
            = berth_order.season.start_season_on
            \-
            = berth_order.season.end_season_on
            )
          %td= berth_order.status.status

          -#%td= link_to 'Vis', berth_order, class: "text-primary"|
          - if current_user.admin?
            -#%td= link_to berth_order.boat.user.email, user_path(berth_order.boat.user_id), class: "text-primary"
            %td= link_to 'Behandle', edit_berth_order_path(berth_order), class: "text-primary"
            -# TODO: Fjerne mulighet for slett?
            -# La heller bestillingen fjernes fra viewet basert på tid, og / eller om den har blitt avvist.
          %td= link_to 'Slett', berth_order, method: :delete, data: { confirm: 'Are you sure?' }, class: "text-primary"
  %br
  - unless current_user.admin?
    = link_to 'Bestill båtplass', new_berth_order_path, class: "btn btn-primary btn-lg text-light btn-sm"

app/views/berth_orders/new.html.haml
= render 'form'

app/views/berth_orders/show.html.haml
= render 'step_guide'

%div.container.text-center#lastPage
  %p
    %b Ordrenummer:
    = @berth_order.id
  %p
    %b Båtnavn:
    = @berth_order.boat.name
  %p
    %b Sesong:
    = "#{@berth_order.season.title}" + " ("+ "#{@berth_order.season.start_season_on}" + " - " + "#{@berth_order.season.end_season_on}" + ")"
  %p
    %b Status:
    = @berth_order.status.status

  = link_to 'Liste over bestillinger', berth_orders_path, class: "text-primary"