config/routes.rb
# == Route Map
#
#                   Prefix Verb   URI Pattern                      Controller#Action
#                  seasons GET    /seasons(.:format)               seasons#index
#                          POST   /seasons(.:format)               seasons#create
#               new_season GET    /seasons/new(.:format)           seasons#new
#              edit_season GET    /seasons/:id/edit(.:format)      seasons#edit
#                   season GET    /seasons/:id(.:format)           seasons#show
#                          PATCH  /seasons/:id(.:format)           seasons#update
#                          PUT    /seasons/:id(.:format)           seasons#update
#                          DELETE /seasons/:id(.:format)           seasons#destroy
#         new_user_session GET    /users/sign_in(.:format)         devise/sessions#new
#             user_session POST   /users/sign_in(.:format)         devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)        devise/sessions#destroy
#        new_user_password GET    /users/password/new(.:format)    devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)   devise/passwords#edit
#            user_password PATCH  /users/password(.:format)        devise/passwords#update
#                          PUT    /users/password(.:format)        devise/passwords#update
#                          POST   /users/password(.:format)        devise/passwords#create
# cancel_user_registration GET    /users/cancel(.:format)          devise/registrations#cancel
#    new_user_registration GET    /users/sign_up(.:format)         devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)            devise/registrations#edit
#        user_registration PATCH  /users(.:format)                 devise/registrations#update
#                          PUT    /users(.:format)                 devise/registrations#update
#                          DELETE /users(.:format)                 devise/registrations#destroy
#                          POST   /users(.:format)                 devise/registrations#create
#                     root GET    /                                marina#home
#                     home GET    /home(.:format)                  marina#home
#                 boatramp GET    /boatramp(.:format)              marina#boatramp
#                 contacts GET    /contacts(.:format)              contacts#new
#                    index GET    /index(.:format)                 marina#index
#                 batplass GET    /batplass(.:format)              marina#berths
#                tjenester GET    /tjenester(.:format)             marina#services
#                          GET    /contacts(.:format)              contacts#new
#                          POST   /contacts(.:format)              contacts#create
#              new_contact GET    /contacts/new(.:format)          contacts#new
#             berth_orders GET    /berth_orders(.:format)          berth_orders#index
#                          POST   /berth_orders(.:format)          berth_orders#create
#          new_berth_order GET    /berth_orders/new(.:format)      berth_orders#new
#         edit_berth_order GET    /berth_orders/:id/edit(.:format) berth_orders#edit
#              berth_order GET    /berth_orders/:id(.:format)      berth_orders#show
#                          PATCH  /berth_orders/:id(.:format)      berth_orders#update
#                          PUT    /berth_orders/:id(.:format)      berth_orders#update
#                          DELETE /berth_orders/:id(.:format)      berth_orders#destroy
#                    boats GET    /boats(.:format)                 boats#index
#                          POST   /boats(.:format)                 boats#create
#                 new_boat GET    /boats/new(.:format)             boats#new
#                edit_boat GET    /boats/:id/edit(.:format)        boats#edit
#                     boat GET    /boats/:id(.:format)             boats#show
#                          PATCH  /boats/:id(.:format)             boats#update
#                          PUT    /boats/:id(.:format)             boats#update
#                          DELETE /boats/:id(.:format)             boats#destroy
#                    users GET    /users(.:format)                 users#index
#                          POST   /users(.:format)                 users#create
#                 new_user GET    /users/new(.:format)             users#new
#                edit_user GET    /users/:id/edit(.:format)        users#edit
#                     user GET    /users/:id(.:format)             users#show
#                          PATCH  /users/:id(.:format)             users#update
#                          PUT    /users/:id(.:format)             users#update
#                          DELETE /users/:id(.:format)             users#destroy
#                          GET    /                                marina#home

Rails.application.routes.draw do

  resources :seasons
  devise_for :users

  root 'marina#home'
  # Static pages:
  get 'home', to: 'marina#home'
  get 'boatramp', to: 'marina#boatramp'
  get 'contacts', to: 'contacts#new'
  get 'index', to: 'marina#index'
  get 'batplass', to: 'marina#berths'
  get 'tjenester', to: 'marina#services'

  match '/contacts',  to: 'contacts#new', via: 'get'
  resources "contacts", only: [:new, :create]


  resources :berth_orders
  resources :boats
  resources :users
  root 'marina#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/boat.rb
# == Schema Information
#
# Table name: boats
#
#  id         :bigint(8)        not null, primary key
#  width      :decimal(8, 2)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#  name       :string
#

class Boat < ApplicationRecord
  belongs_to :user
  has_many :berth_orders

  validates :name, :uniqueness => {scope: :user_id}
  validates :user_id, :presence => true

  def format_width
    self.width = self.width.to_s.gsub(',', '.')
  end

end

app/controllers/boats_controller.rb
class BoatsController < ApplicationController
  before_action :set_boat, only: [:show, :edit, :update, :destroy]

  # GET /boats
  # GET /boats.json
  def index
    if current_user.admin?
      @boats = Boat.all
    else
      @boats = current_user.boats
    end
  end

  # GET /boats/1
  # GET /boats/1.json
  def show
  end

  # GET /boats/new
  def new
    @boat = Boat.new
  end

  # GET /boats/1/edit
  def edit
  end

  # POST /boats
  # POST /boats.json
  def create
    @boat = Boat.new(boat_params)
    @boat.width = @boat.width.to_s.gsub(',', '.')
    @boat.user = current_user
    respond_to do |format|
      if @boat.save
        format.html { redirect_to new_berth_order_path, notice: 'Boat was successfully created.' }
        format.json { render :show, status: :created, location: @boat }
      else
        format.html { render :new }
        format.json { render json: @boat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boats/1
  # PATCH/PUT /boats/1.json
  def update
    respond_to do |format|
      if @boat.update(boat_params)
        format.html { redirect_to @boat, notice: 'Boat was successfully updated.' }
        format.json { render :show, status: :ok, location: @boat }
      else
        format.html { render :edit }
        format.json { render json: @boat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boats/1
  # DELETE /boats/1.json
  def destroy
    @boat.destroy
    respond_to do |format|
      format.html { redirect_to boats_url, notice: 'Boat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_boat
    @boat = Boat.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def boat_params
    params.require(:boat).permit(:name, :width)
  end
end

app/views/boats/_adminboats.haml
%tbody
%table.table
  %thead
    %tr
      %th{scope: "col"} Båtnavn
      %th{scope: "col"} Bredde

      %th
      %th
      %th

  - @boats.each do |boat|
    %tr
      %td= boat.name
      %td= boat.width
      %td= link_to 'Vis', boat, class: "text-primary"
      %td= link_to 'Endre', edit_boat_path(boat), class: "text-primary"
      %td= link_to 'Slett', boat, method: :delete, data: { confirm: 'Er du sikker?' }, class: "text-primary"

app/views/boats/_berth_order.html.haml
%h3 Leie båtplass
%div.form-row
  = f.hidden_field :boat_id, value: @boat.id
  %div.form-group.col-md-3
    = f.label :fra
    = # f.date_field :start_berth_order, class: "form-control"
  %div.form-group-col-md-3
    = f.label :til
    = #f.date_field :end_berth_order, class: "form-control"

app/views/boats/_calc.html.haml
%form
  %div.form-row
    %div.form-group.col-md-2
      %input#calcInput{type: :text, class: "form-control"}
      %label fot
    %div.form-group.col-md-3
      %input#calcSolution{type: :label, readonly: true, class: "form-control"}
      %label meter

app/views/boats/_form.html.haml
= form_for @boat do |f|
  - if @boat.errors.any?
    #error_explanation
      %h2= "#{@boat.errors.count} feil hindret denne båten fra å bli lagret:"
      %ul
        - @boat.errors.full_messages.each do |message|
          %li= message

  %div.form-row
    %div.form-group.col-md-6
      = f.label :name, 'Båtnavn'
      = f.text_field :name, placeholder: "Dronning Maud II", class: "form-control"
    %div.form-group.col-md-6
      = f.label :width, 'Bredde'
      \ (meter)
      = f.text_field :width, placeholder: "3.4", class: "form-control"
    = f.submit 'Lagre', class: "btn btn-primary btn-lg text-light btn-sm"
    = link_to 'Tilbake', boats_path, class: "btn btn-primary btn-lg text-light btn-sm"
    %div

app/views/boats/_service_order.html.haml
%h3 Legg til tjenester
%div.form-row
  %div.form-group.col-md-3
    = f.label :fra
    = f.date_field :start_service_order, class: "form-control"
  %div.form-group-col-md-3
    = f.label :til
    = f.date_field :end_service_order, class: "form-control"

app/views/boats/_userboats.haml
%table.table
  %thead
    %tr
      %th{scope: "col"} Båtnavn
      %th{scope: "col"} Bredde
      %th
      %th
      %th

  %tbody
    - @boats.each do |boat|
      - if boat.user == current_user
        %tr
          %td= boat.name
          %td= boat.width
          %td= link_to 'Vis', boat, class: "text-primary"
          %td= link_to 'Endre', edit_boat_path(boat), class: "text-primary"
          %td= link_to 'Slett', boat, method: :delete, data: { confirm: 'Er du sikker?' }, class: "text-primary"

app/views/boats/edit.html.haml
%div.container
  %h1 Endre båt

  = render 'form', button_text: "Endre"

app/views/boats/index.html.haml
%div.container
  %h1 Båter, oversikt
  - if current_user.admin?
    = render "adminboats"

  - else
    = render "userboats"
    %br
      = link_to 'Legg til båt', new_boat_path, class: "btn btn-primary btn-lg text-light btn-sm"
  %br

app/views/boats/new.html.haml
%div.container
  %h1 Legg til båt
  %div.row
    %div.col
      = render 'form', button_text: "Legg til"

    %div.col-4
      %h4 Fot til meter:
      = render 'calc'

app/views/boats/show.html.haml
%div.container
  %table.table
    %thead
      %tr
        %th{scope: "col"} Båtnavn
        %th{scope: "col"} Bredde
      %tr
        %td= @boat.name
        %td= @boat.width
        %td


  = link_to 'Endre', edit_boat_path(@boat), class: "btn btn-primary btn-lg text-light btn-sm"
  \
  = link_to 'Tilbake', boats_path, class: "btn btn-primary btn-lg text-light btn-sm"